#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/:/usr/local/sbin
set -e

cr=`echo '\n.'`
cr=${cr%.}

cget() { curl -sf "http://127.0.0.1:8500/v1/kv/vault/config/$1?raw"; }

if [ ! $(cget root-token) ]; then
  echo "Initialize Vault"
  vault init | tee /tmp/vault.init > /dev/null

  # Store master keys in consul for operator to retrieve and remove
  COUNTER=1
  cat /tmp/vault.init | grep '^Unseal' | awk '{print $4}' | for key in $(cat -); do
    curl -sfX PUT 127.0.0.1:8500/v1/kv/vault/config/unseal-key-$COUNTER -d $key
    COUNTER=$((COUNTER + 1))
  done

  export VAULT_ROOT_TOKEN=$(cat /tmp/vault.init | grep '^Initial' | awk '{print $4}')
  curl -sfX PUT 127.0.0.1:8500/v1/kv/vault/config/root-token -d $VAULT_ROOT_TOKEN

  echo "Remove master keys from disk"
  shred /tmp/vault.init

else
  echo "Vault has already been initialized, skipping."
fi

echo "Unsealing Vault"
vault unseal $(cget unseal-key-1)
vault unseal $(cget unseal-key-2)
vault unseal $(cget unseal-key-3)

echo "Vault setup complete."
echo "The vault unseal keys and root token have been stored in Consul K/V."
echo "  /vault/config/root-token"
echo "  /vault/config/unseal-key-{1..5}"
